
global:
  trace:
    verbose: true

pipelines:
  - name: tap
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
    routing-policy:
      forward: [ elastic, console]
      dropped: []
      
  - name: console
    stdout:
      mode: text

  - name: elastic
    elasticsearch:
      server: "http://localhost:9200/"
      index:  "dnscollector"
      bulk-size: 5242880
      flush-interval: 10
      compression: none
      bulk-channel-size: 10